# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-org1
  name: peer0-org1
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
  - name: "peer-core"
    port: 7051
    targetPort: 7051
  selector:
    app: peer0-org1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-org1
    metrics-service: "true"
  name: peer0-org1-metrics
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
  - name: "peer-metrics"
    port: 9443
    targetPort: 9443
  selector:
    app: peer0-org1
