# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: fpccc-peer0-org1
  namespace: hyperledger
  labels:
    app: fpccc-peer0-org1
spec:
  ports:
    - name: grpc
      port: 9999
      targetPort: 9999
  selector:
    app: fpccc-peer0-org1
