# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ca-org2
  name: ca-org2
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
    - name: "https"
      port: 7054
      targetPort: 7054
  selector:
    app: ca-org2
