name: Dependabot go mod tidy

on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Go Tidy
        run: make gotidy

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: go mod tidy
          commit_options: "--no-verify --signoff"
